// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPassword = `-- name: CreatePassword :one
INSERT INTO passwords (user_id, hashed_password, created_at)
VALUES ($1, $2, $3)
RETURNING user_id, hashed_password, created_at
`

type CreatePasswordParams struct {
	UserID         pgtype.UUID
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error) {
	row := q.db.QueryRow(ctx, createPassword, arg.UserID, arg.HashedPassword, arg.CreatedAt)
	var i Password
	err := row.Scan(&i.UserID, &i.HashedPassword, &i.CreatedAt)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, created_at, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token, created_at, updated_at, user_id, expires_at
`

type CreateRefreshTokenParams struct {
	Token     string
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, deleteRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserFromRefreshTok = `-- name: GetUserFromRefreshTok :one
SELECT token, created_at, updated_at, user_id, expires_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetUserFromRefreshTok(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getUserFromRefreshTok, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}
