// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, content, created_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, content, created_at
`

type CreateMessageParams struct {
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Content, arg.CreatedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT t1.user_id, t1.content, t1.created_at, t2.username
FROM messages t1
JOIN users t2 ON t1.user_id = t2.user_id
ORDER BY t1.created_at
`

type ListMessagesRow struct {
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
	Username  string
}

func (q *Queries) ListMessages(ctx context.Context) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
