// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Password struct {
	UserID         pgtype.UUID
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	UserID   pgtype.UUID
	Username string
	Email    string
}
