// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, username)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type CreateUserParams struct {
	UserID   pgtype.UUID
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.UserID, arg.Username)
	return err
}
