services:
  server:
    build:
      context: .
      target: dev
    restart: always
    command: >
      /bin/sh -c
      "wgo -poll 1s -file .go -file .templ -xfile ._templ.go pnpm run build:css :: templ generate :: go build -o /bin/main main.go :: /bin/main"
    volumes:
      - .:/goapp
      - /goapp/node_modules
