# https://taskfile.dev

version: "3"

dotenv:
  - .env

tasks:
  compose::up:
    cmds:
      - docker compose --env-file ./.env -f compose.yaml -f compose.dev.yaml up

  compose::down:
    cmds:
      - docker compose -f compose.yaml -f compose.dev.yaml down

  compose::up-build:
    cmds:
      - docker compose --env-file ./.env -f compose.yaml -f compose.dev.yaml up --build

  db::up:
    cmds:
      - goose up

  db::reset:
    cmds:
      - goose reset

  dev:
    cmds:
      - task: css
      - task: templ
      - task: server
    silent: true

  server:
    cmds:
      - golangci-lint && govulncheck
      - "pnpm run watch:css & wgo -file .templ -xfile ._templ.go -file .go templ generate :: go run ./main.go"

  templ:
    cmds:
      - templ generate

    sources:
      - ./components/**/*.templ
    generates:
      - ./components/**/*_templ.go

  css:
    cmds:
      - pnpm run build:css

    sources:
      - ./static/input.css
    generates:
      - ./static/output.css
