# https://taskfile.dev

version: "3"

dotenv:
  - .env

tasks:
  compose::up:
    cmds:
      - docker compose --env-file ./.env -f compose.yaml -f compose.dev.yaml up

  compose::down:
    cmds:
      - docker compose -f compose.yaml -f compose.dev.yaml down

  compose::up-build:
    cmds:
      - docker compose --env-file ./.env -f compose.yaml -f compose.dev.yaml up --build

  db::up:
    cmds:
      - goose up

  db::reset:
    cmds:
      - goose reset
