# https://taskfile.dev

version: "3"

tasks:
  up:
    cmds:
      - dotenvx run -- docker compose -f compose.yaml -f compose.dev.yaml up

  down:
    cmds:
      - docker compose -f compose.yaml -f compose.dev.yaml down

  up-build:
    cmds:
      - dotenvx run -- docker compose -f compose.yaml -f compose.dev.yaml up --build

  dev:
    cmds:
      - task: css
      - task: templ
      - task: server
    silent: true

  server:
    cmds:
      - golangci-lint && govulncheck
      - "wgo -file .templ -xfile ._templ.go -file .go go build -o ./bin/ ./main.go :: ./bin/main"

  templ:
    cmds:
      - templ generate

    sources:
      - ./components/**/*.templ
    generates:
      - ./components/**/*_templ.go

  css:
    cmds:
      - pnpm run build:css

    sources:
      - ./static/input.css
    generates:
      - ./static/output.css
