// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package chat

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/johndosdos/chatter/components"

func ChatLayout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-zinc-950 flex items-center justify-center font-sans\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ChatWindow().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\t\t\t\tlet messageArea = document.getElementById(\"message-area\");\n\n        document.body.addEventListener(\"htmx:responseError\", (event) => {\n          if (event.detail.xhr.status === 401) {\n            htmx.ajax(\"GET\", \"/api/token/refresh\");\n          }\n        });\n\n\t\t\t\t// Add auto-scroll mechanism on new messages, with animation.\n\t\t\t\tdocument.body.addEventListener(\"htmx:oobAfterSwap\", () => {\n\t\t\t\t\tmessageArea.scroll({ top: messageArea.scrollHeight, behavior: \"smooth\" })\n\t\t\t\t});\n\n        let initialLoad = false;\n        document.body.addEventListener(\"htmx:wsOpen\", () => {\n          initialLoad = true;\n        });\n\n        let lastMsg = messageArea?.lastElementChild;\n        let since = lastMsg?.dataset.timestamp;\n        document.body.addEventListener(\"htmx:wsConnecting\", () => {\n          if (!initialLoad) {\n            return;\n          }\n\n          lastMsg = messageArea?.lastElementChild;\n          since = lastMsg?.dataset.timestamp;\n          if (!since) {\n            return\n          }\n\n          let url = new URL(\"/messages\", window.location.origin);\n          url.searchParams.set(\"since\", since);\n\n          htmx.ajax(\"GET\", url.toString(), { target: \"#message-area\", swap: \"beforeend\" });\n        });\n\t\t\t</script></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
